jobs:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode12
      podfile: ios/Podfile
      cache:
        - yarn
        - cocoapods
      before_install:
        - nvm install node
        - npm install -g yarn
      install:
        - brew tap wix/brew
        - brew install applesimutils
        - gem install fastlane
        - gem install cocoapods
        - yarn
        - cd ios && pod install && cd ..
      script:
        - yarn ios
    - language: android
      os: linux
      dist: trusty
      android:
        components:
          - tools
          - platform-tools
      jdk:
        - oraclejdk8
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        yarn: true
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      before_install:
        - openssl aes-256-cbc -k "$SECRET_PASSWORD" -in THUInfo.jks.enc -out android/app/THUInfo.jks -d
        - nvm install node
        - npm install -g yarn
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install gradle 5.6.4
        - yes | sdkmanager "build-tools;30.0.1"
      install:
        - yarn
      script:
        - cd android && gradle assembleRelease && cd ..
      before_deploy:
        - mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/THUInfo_release_$TRAVIS_TAG.apk
      deploy:
        provider: releases
        api_key:
          secure: RMf2ORhxG/9TSsu7x0GLLaWerg9fTAWoVvNEa/ggb56Geo4w3Cg8mZoXRq708HoqNdOyD0kFsVIx3xW45EvZvZp0Os/2zza6T8jmzg59zrmUmBAHFg4+ks7Ox0E3QwBozN7XJwuLCEuGHnOw6tNRTsfd84hT+lBr3Zvzkfbsn1S5ZkP8SoHZQ8TmuYWd+34eFPn7u2mjjGHe/sxhXPnqtKZKfKTpWPoHE+qyGR3ni9dxI1tiMfxzCFi4MGyHKndntcUYxSYGJ09oYfNNqgAasV1yZxhXg0LUFsi5veE4b20rJ5shjPnTbXPM3PeT/BK74X2zfmUT+vXoOay/i1RX1peW1YT/bZ8zB8K8FL7ChbNVZ8DOQM/TevEYn7Y9tTI46MqJVLz61T2DKnAo6l074HW+X37AQly+u995PsMs62YaGKcWG+XXZBPN0rlgmwd4DxTScIN7f/v3fps7kpca+vXdJQnDhAaR6wR7UZsHwqYeLvm7JyNjrCDW814a0/6v147XPiPq7EVA8LAalj9vijZ9iOApWx/wv+z9ZoQ7y5VAZot6pqI/p6VTj7MBOwM0AfMFyC8hT9PReGIumLoRy0Msf1UdpqjS7z72KKn0xu8qmK4vuDkEOP3Tx+lz/yGQYlmKPEo5o4FnhX4yMq1XsttS8pmsXyRSAF/Ewy6c9Ug=
        file: android/app/build/outputs/apk/release/THUInfo_release_$TRAVIS_TAG.apk
        on:
          tags: true
          repo: UNIDY2002/THUInfo
        skip_cleanup: true
        overwrite: true
    - language: node_js
      os: linux
      dist: trusty
      node_js:
        - "14"
      cache: yarn
      install:
        - yarn
      script:
        - yarn lint
        - yarn test
