name: Static check for pull requests

on: pull_request

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup caching
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-${{ runner.OS }}-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            cache-${{ runner.OS }}-
      - name: Install dependencies
        run: |
          yarn
      - name: Run tests
        run: |
          yarn lint
          yarn test
